-- 코드를 입력하세요
SELECT a.PRODUCT_CODE, SUM(a.PRICE*b.SALES_AMOUNT) AS "SALES"
FROM PRODUCT a
JOIN OFFLINE_SALE b ON a.PRODUCT_ID=b.PRODUCT_ID
GROUP BY a.PRODUCT_CODE
ORDER BY SALES DESC, a.PRODUCT_CODE ASC

-- 지금 조인까지는 했고 같은 Product_code는 더해줘야함