-- 코드를 입력하세요
SELECT distinct a.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR a
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b ON a.CAR_ID=b.CAR_ID
WHERE a.CAR_TYPE = '세단' AND b.START_DATE Between '2022-10-01' AND '2022-10-31'
ORDER by a.CAR_ID desc;