-- 코드를 입력하세요
SELECT  a.TITLE,a.BOARD_ID, b.REPLY_ID,b.WRITER_ID, b.CONTENTS,TO_CHAR(b.CREATED_DATE,'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD a
JOIN USED_GOODS_REPLY b ON a.BOARD_ID=b.BOARD_ID
where TO_CHAR(a.CREATED_DATE,'YYYY-MM') = '2022-10'
ORDER BY b.CREATED_DATE, a.TITLE;